language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE byob_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: 21GJfMO8/cN+L21s2yuQC196SMf4gXpYRyXXiuBE6ULRe9nyXEfphqMuxz28qbFIRZz9Z+q3AIkStViaZAPAQFDIsk3TG2EyX48twfKjbj3f7ast5wBMzNgvtV6KMddg7yZO/jByakth+cFRySCej8pftf7hK5tsvreAWc7/nzSdPM6tl+YpcHpLi31HGeBCvcKJZPiDQqwubJFIBzawZoW1Fj1tEpk+k5RBnKrHSJpc79BWJjCkDDe0Xw+KYLTENbUaU0jYVN2Y5r97cNLwvJlkpK+AgkVbBe3o2y8sc8Iy9RWbHVJPR1Zp6QjfdGEhToJpaDZ+4wPuQ3d3cOyzmfKfm6eskepXAzhuTLpyebjaIt8tLUWpohC6JnFqMjyZU51inGAWhZHs6/ISIea+ka/hdJMKjdenntHhaL1m0FtIEtbp4bc33Id+6pSDe7iJDyWxfrlgMZ2GI0DXWro/qvAR/XJ/g6BieMV8ssta4MUxYMayZJHRIePPtUoV4oI9qJEE8GjWu04B4XLsjY2qtD5D9smNAyXV03heD30wkLxyUTVSGVZfq+6xzNZK3Be5Ques+UkzKHnXWISw3z4W9z1s5Dl9nhQawJpv9fDsupvMQ8S1bvqO/oaNmnkARYClZbu1Y6b0aQ+47uGzhxgN83PQBMG8wm5ncokf70T//d8=
  app: byob-ch-mh
  skip_cleanup: true
